package SensorCamera;


/**
* SensorCamera/Image.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class Image implements org.omg.CORBA.portable.IDLEntity
{
  public long time = (long)0;
  public SensorCamera.Warning warning = null;

  public Image ()
  {
  } // ctor

  public Image (long _time, SensorCamera.Warning _warning)
  {
    time = _time;
    warning = _warning;
  } // ctor

} // class Image
