package SensorCamera;

/**
* SensorCamera/ImageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class ImageHolder implements org.omg.CORBA.portable.Streamable
{
  public SensorCamera.Image value = null;

  public ImageHolder ()
  {
  }

  public ImageHolder (SensorCamera.Image initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SensorCamera.ImageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SensorCamera.ImageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SensorCamera.ImageHelper.type ();
  }

}
