package SensorCamera;


/**
* SensorCamera/ImageHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

abstract public class ImageHelper
{
  private static String  _id = "IDL:SensorCamera/Image:1.0";

  public static void insert (org.omg.CORBA.Any a, SensorCamera.Image that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SensorCamera.Image extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "time",
            _tcOf_members0,
            null);
          _tcOf_members0 = SensorCamera.WarningHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "warning",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (SensorCamera.ImageHelper.id (), "Image", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SensorCamera.Image read (org.omg.CORBA.portable.InputStream istream)
  {
    SensorCamera.Image value = new SensorCamera.Image ();
    value.time = istream.read_longlong ();
    value.warning = SensorCamera.WarningHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SensorCamera.Image value)
  {
    ostream.write_longlong (value.time);
    SensorCamera.WarningHelper.write (ostream, value.warning);
  }

}
