package SensorCamera;

/**
* SensorCamera/SensorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class SensorHolder implements org.omg.CORBA.portable.Streamable
{
  public SensorCamera.Sensor value = null;

  public SensorHolder ()
  {
  }

  public SensorHolder (SensorCamera.Sensor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SensorCamera.SensorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SensorCamera.SensorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SensorCamera.SensorHelper.type ();
  }

}
