package SensorCamera;


/**
* SensorCamera/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
