package SensorCamera;


/**
* SensorCamera/SensorPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/F/Workspace3/CamCobra_u1167937test/camera.idl
* Thursday, 28 April 2016 23:12:35 o'clock BST
*/

public class SensorPOATie extends SensorPOA
{

  // Constructors

  public SensorPOATie ( SensorCamera.SensorOperations delegate ) {
      this._impl = delegate;
  }
  public SensorPOATie ( SensorCamera.SensorOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public SensorCamera.SensorOperations _delegate() {
      return this._impl;
  }
  public void _delegate (SensorCamera.SensorOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String cameraname ()
  {
    return _impl.cameraname();
  } // cameraname
  public void cameraname (String newCameraname)
  {
    _impl.cameraname(newCameraname);
  } // cameraname

  public SensorCamera.Image current_image ()
  {
    return _impl.current_image();
  } // current_image

  public SensorCamera.Warning image_warning ()
  {
    return _impl.image_warning();
  } // image_warning
  public void image_warning (SensorCamera.Warning newImage_warning)
  {
    _impl.image_warning(newImage_warning);
  } // image_warning

  public SensorCamera.Image get_image ()
  {
    return _impl.get_image();
  } // get_image

  public SensorCamera.SensorPackage.Status status ()
  {
    return _impl.status();
  } // status

  public void record_image (double value)
  {
    _impl.record_image(value);
  } // record_image

  public String getstatus ()
  {
    return _impl.getstatus();
  } // getstatus

  public void switch_on ()
  {
    _impl.switch_on();
  } // switch_on

  public void switch_off ()
  {
    _impl.switch_off();
  } // switch_off

  public void reset ()
  {
    _impl.reset();
  } // reset

  public boolean camera_on ()
  {
    return _impl.camera_on();
  } // camera_on

  public boolean camera_off ()
  {
    return _impl.camera_off();
  } // camera_off

  private SensorCamera.SensorOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class SensorPOATie
