package SensorCamera;


/**
* SensorCamera/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public interface SensorOperations 
{
  String cameraname ();
  void cameraname (String newCameraname);
  SensorCamera.Image current_image ();
  SensorCamera.Warning image_warning ();
  void image_warning (SensorCamera.Warning newImage_warning);
  SensorCamera.Image get_image ();
  SensorCamera.SensorPackage.Status status ();
  void record_image (double value);
  String getstatus ();
  void switch_on ();
  void switch_off ();
  void reset ();
  boolean camera_on ();
  boolean camera_off ();
} // interface SensorOperations
