package SensorCamera;


/**
* SensorCamera/Warning.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class Warning implements org.omg.CORBA.portable.IDLEntity
{
  public double value = (double)0;

  public Warning ()
  {
  } // ctor

  public Warning (double _value)
  {
    value = _value;
  } // ctor

} // class Warning
