package RegionalMonitoringCentre;

/**
* RegionalMonitoringCentre/AlarmDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/rmc.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class AlarmDataHolder implements org.omg.CORBA.portable.Streamable
{
  public RegionalMonitoringCentre.AlarmData value = null;

  public AlarmDataHolder ()
  {
  }

  public AlarmDataHolder (RegionalMonitoringCentre.AlarmData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RegionalMonitoringCentre.AlarmDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RegionalMonitoringCentre.AlarmDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RegionalMonitoringCentre.AlarmDataHelper.type ();
  }

}
