package RegionalMonitoringCentre;


/**
* RegionalMonitoringCentre/AlarmData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/rmc.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class AlarmData implements org.omg.CORBA.portable.IDLEntity
{
  public LocalMonitoringStation.Alert aReading[] = null;
  public String aConfirmingSensor = null;

  public AlarmData ()
  {
  } // ctor

  public AlarmData (LocalMonitoringStation.Alert[] _aReading, String _aConfirmingSensor)
  {
    aReading = _aReading;
    aConfirmingSensor = _aConfirmingSensor;
  } // ctor

} // class AlarmData
