package RegionalMonitoringCentre;


/**
* RegionalMonitoringCentre/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/rmc.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public interface RMCOperations 
{
  void add_station (LocalMonitoringStation.LMS lms);
  void remove_station (LocalMonitoringStation.LMS station);
  LocalMonitoringStation.LMS get_station (String station);
  String[] get_stations ();
  String[] get_zones (String station);
  SensorCamera.Sensor[] get_sensors (String station, String zone);
  String[][] get_sensors_data (String station, String zone);
  void register_user (RegionalMonitoringCentre.User aUser, String lms, String zone);
  RegionalMonitoringCentre.Warning[] get_all_warnings (String lms, String zone);
} // interface RMCOperations
