package RegionalMonitoringCentre;


/**
* RegionalMonitoringCentre/RMCPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/F/Workspace3/CamCobra_u1167937test/rmc.idl
* Thursday, 28 April 2016 23:40:40 o'clock BST
*/

public class RMCPOATie extends RMCPOA
{

  // Constructors

  public RMCPOATie ( RegionalMonitoringCentre.RMCOperations delegate ) {
      this._impl = delegate;
  }
  public RMCPOATie ( RegionalMonitoringCentre.RMCOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public RegionalMonitoringCentre.RMCOperations _delegate() {
      return this._impl;
  }
  public void _delegate (RegionalMonitoringCentre.RMCOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void add_station (LocalMonitoringStation.LMS lms)
  {
    _impl.add_station(lms);
  } // add_station

  public void remove_station (LocalMonitoringStation.LMS station)
  {
    _impl.remove_station(station);
  } // remove_station

  public LocalMonitoringStation.LMS get_station (String station)
  {
    return _impl.get_station(station);
  } // get_station

  public String[] get_stations ()
  {
    return _impl.get_stations();
  } // get_stations

  public String[] get_zones (String station)
  {
    return _impl.get_zones(station);
  } // get_zones

  public SensorCamera.Sensor[] get_sensors (String station, String zone)
  {
    return _impl.get_sensors(station, zone);
  } // get_sensors

  public String[][] get_sensors_data (String station, String zone)
  {
    return _impl.get_sensors_data(station, zone);
  } // get_sensors_data

  public void register_user (RegionalMonitoringCentre.User aUser, String lms, String zone)
  {
    _impl.register_user(aUser, lms, zone);
  } // register_user

  public RegionalMonitoringCentre.Warning[] get_all_warnings (String lms, String zone)
  {
    return _impl.get_all_warnings(lms, zone);
  } // get_all_warnings

  private RegionalMonitoringCentre.RMCOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RMCPOATie
