package RegionalMonitoringCentre;


/**
* RegionalMonitoringCentre/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/rmc.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String email = null;
  public String password = null;

  public User ()
  {
  } // ctor

  public User (String _name, String _email, String _password)
  {
    name = _name;
    email = _email;
    password = _password;
  } // ctor

} // class User
