package RegionalMonitoringCentre;


/**
* RegionalMonitoringCentre/Warning.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/rmc.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class Warning implements org.omg.CORBA.portable.IDLEntity
{
  public String lms = null;
  public String zone = null;
  public String severity = null;
  public long timestamp = (long)0;

  public Warning ()
  {
  } // ctor

  public Warning (String _lms, String _zone, String _severity, long _timestamp)
  {
    lms = _lms;
    zone = _zone;
    severity = _severity;
    timestamp = _timestamp;
  } // ctor

} // class Warning
