package RegionalMonitoringCentre;

/**
* RegionalMonitoringCentre/WarningHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/rmc.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class WarningHolder implements org.omg.CORBA.portable.Streamable
{
  public RegionalMonitoringCentre.Warning value = null;

  public WarningHolder ()
  {
  }

  public WarningHolder (RegionalMonitoringCentre.Warning initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RegionalMonitoringCentre.WarningHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RegionalMonitoringCentre.WarningHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RegionalMonitoringCentre.WarningHelper.type ();
  }

}
