package RegionalMonitoringCentre;


/**
* RegionalMonitoringCentre/WarningsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/rmc.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

abstract public class WarningsHelper
{
  private static String  _id = "IDL:RegionalMonitoringCentre/Warnings:1.0";

  public static void insert (org.omg.CORBA.Any a, RegionalMonitoringCentre.Warning[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RegionalMonitoringCentre.Warning[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = RegionalMonitoringCentre.WarningHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (RegionalMonitoringCentre.WarningsHelper.id (), "Warnings", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RegionalMonitoringCentre.Warning[] read (org.omg.CORBA.portable.InputStream istream)
  {
    RegionalMonitoringCentre.Warning value[] = null;
    int _len0 = istream.read_long ();
    value = new RegionalMonitoringCentre.Warning[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = RegionalMonitoringCentre.WarningHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RegionalMonitoringCentre.Warning[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      RegionalMonitoringCentre.WarningHelper.write (ostream, value[_i0]);
  }

}
