package LocalMonitoringStation;


/**
* LocalMonitoringStation/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/lms.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public interface LMSOperations 
{
  String name ();
  void add_camera (SensorCamera.Sensor aSensor, String aZone);
  void record_camera (SensorCamera.Sensor aSensor, String aZone, SensorCamera.Image aReading);
  void raise_alerts (SensorCamera.Sensor aSensor, String aZone, SensorCamera.Image aReading);
  String[] get_zones ();
  SensorCamera.Sensor[] get_camera (String zone);
  LocalMonitoringStation.Log[] retrieve_logs (String sensor, String zone);
  LocalMonitoringStation.Alert[] retrieve_alerts (String sensor, String zone);
} // interface LMSOperations
