package LocalMonitoringStation;


/**
* LocalMonitoringStation/Log.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/lms.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class Log implements org.omg.CORBA.portable.IDLEntity
{
  public String sensor = null;
  public long timestamp = (long)0;
  public SensorCamera.Warning level = null;

  public Log ()
  {
  } // ctor

  public Log (String _sensor, long _timestamp, SensorCamera.Warning _level)
  {
    sensor = _sensor;
    timestamp = _timestamp;
    level = _level;
  } // ctor

} // class Log
