package LocalMonitoringStation;

/**
* LocalMonitoringStation/SensorEventsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/lms.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class SensorEventsHolder implements org.omg.CORBA.portable.Streamable
{
  public LocalMonitoringStation.SensorEvents value = null;

  public SensorEventsHolder ()
  {
  }

  public SensorEventsHolder (LocalMonitoringStation.SensorEvents initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LocalMonitoringStation.SensorEventsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LocalMonitoringStation.SensorEventsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LocalMonitoringStation.SensorEventsHelper.type ();
  }

}
