package LocalMonitoringStation;


/**
* LocalMonitoringStation/SensorsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/lms.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class SensorsHolder implements org.omg.CORBA.portable.Streamable
{
  public SensorCamera.Sensor value[] = null;

  public SensorsHolder ()
  {
  }

  public SensorsHolder (SensorCamera.Sensor[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LocalMonitoringStation.SensorsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LocalMonitoringStation.SensorsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LocalMonitoringStation.SensorsHelper.type ();
  }

}
