package LocalMonitoringStation;


/**
* LocalMonitoringStation/SensorEventsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/lms.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

abstract public class SensorEventsHelper
{
  private static String  _id = "IDL:LocalMonitoringStation/SensorEvents:1.0";

  public static void insert (org.omg.CORBA.Any a, LocalMonitoringStation.SensorEvents that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LocalMonitoringStation.SensorEvents extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LocalMonitoringStation.SensorEventsHelper.id (), "SensorEvents");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LocalMonitoringStation.SensorEvents read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SensorEventsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LocalMonitoringStation.SensorEvents value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LocalMonitoringStation.SensorEvents narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LocalMonitoringStation.SensorEvents)
      return (LocalMonitoringStation.SensorEvents)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LocalMonitoringStation._SensorEventsStub stub = new LocalMonitoringStation._SensorEventsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LocalMonitoringStation.SensorEvents unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LocalMonitoringStation.SensorEvents)
      return (LocalMonitoringStation.SensorEvents)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LocalMonitoringStation._SensorEventsStub stub = new LocalMonitoringStation._SensorEventsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
