package LocalMonitoringStation;


/**
* LocalMonitoringStation/SensorEvents.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/lms.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public interface SensorEvents extends SensorEventsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SensorEvents
