package LocalMonitoringStation;


/**
* LocalMonitoringStation/SensorEventsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/lms.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public abstract class SensorEventsPOA extends org.omg.PortableServer.Servant
 implements LocalMonitoringStation.SensorEventsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_lmsname", new java.lang.Integer (0));
    _methods.put ("_get_sensor", new java.lang.Integer (1));
    _methods.put ("record_log", new java.lang.Integer (2));
    _methods.put ("record_alarm", new java.lang.Integer (3));
    _methods.put ("get_logs", new java.lang.Integer (4));
    _methods.put ("get_alerts", new java.lang.Integer (5));
    _methods.put ("get_timelogs", new java.lang.Integer (6));
    _methods.put ("get_timealerts", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LocalMonitoringStation/SensorEvents/_get_lmsname
       {
         String $result = null;
         $result = this.lmsname ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // LocalMonitoringStation/SensorEvents/_get_sensor
       {
         SensorCamera.Sensor $result = null;
         $result = this.sensor ();
         out = $rh.createReply();
         SensorCamera.SensorHelper.write (out, $result);
         break;
       }

       case 2:  // LocalMonitoringStation/SensorEvents/record_log
       {
         LocalMonitoringStation.Log aLog = LocalMonitoringStation.LogHelper.read (in);
         this.record_log (aLog);
         out = $rh.createReply();
         break;
       }

       case 3:  // LocalMonitoringStation/SensorEvents/record_alarm
       {
         LocalMonitoringStation.Alert anAlert = LocalMonitoringStation.AlertHelper.read (in);
         this.record_alarm (anAlert);
         out = $rh.createReply();
         break;
       }

       case 4:  // LocalMonitoringStation/SensorEvents/get_logs
       {
         LocalMonitoringStation.Log $result[] = null;
         $result = this.get_logs ();
         out = $rh.createReply();
         LocalMonitoringStation.LogsHelper.write (out, $result);
         break;
       }

       case 5:  // LocalMonitoringStation/SensorEvents/get_alerts
       {
         LocalMonitoringStation.Alert $result[] = null;
         $result = this.get_alerts ();
         out = $rh.createReply();
         LocalMonitoringStation.AlertsHelper.write (out, $result);
         break;
       }

       case 6:  // LocalMonitoringStation/SensorEvents/get_timelogs
       {
         long timestamp = in.read_longlong ();
         LocalMonitoringStation.Log $result[] = null;
         $result = this.get_timelogs (timestamp);
         out = $rh.createReply();
         LocalMonitoringStation.LogsHelper.write (out, $result);
         break;
       }

       case 7:  // LocalMonitoringStation/SensorEvents/get_timealerts
       {
         long timestamp = in.read_longlong ();
         LocalMonitoringStation.Alert $result[] = null;
         $result = this.get_timealerts (timestamp);
         out = $rh.createReply();
         LocalMonitoringStation.AlertsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LocalMonitoringStation/SensorEvents:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SensorEvents _this() 
  {
    return SensorEventsHelper.narrow(
    super._this_object());
  }

  public SensorEvents _this(org.omg.CORBA.ORB orb) 
  {
    return SensorEventsHelper.narrow(
    super._this_object(orb));
  }


} // class SensorEventsPOA
