package LocalMonitoringStation;


/**
* LocalMonitoringStation/SensorEventsPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/F/Workspace3/CamCobra_u1167937test/lms.idl
* Thursday, 28 April 2016 23:08:05 o'clock BST
*/

public class SensorEventsPOATie extends SensorEventsPOA
{

  // Constructors

  public SensorEventsPOATie ( LocalMonitoringStation.SensorEventsOperations delegate ) {
      this._impl = delegate;
  }
  public SensorEventsPOATie ( LocalMonitoringStation.SensorEventsOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public LocalMonitoringStation.SensorEventsOperations _delegate() {
      return this._impl;
  }
  public void _delegate (LocalMonitoringStation.SensorEventsOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String lmsname ()
  {
    return _impl.lmsname();
  } // lmsname

  public SensorCamera.Sensor sensor ()
  {
    return _impl.sensor();
  } // sensor

  public void record_log (LocalMonitoringStation.Log aLog)
  {
    _impl.record_log(aLog);
  } // record_log

  public void record_alarm (LocalMonitoringStation.Alert anAlert)
  {
    _impl.record_alarm(anAlert);
  } // record_alarm

  public LocalMonitoringStation.Log[] get_logs ()
  {
    return _impl.get_logs();
  } // get_logs

  public LocalMonitoringStation.Alert[] get_alerts ()
  {
    return _impl.get_alerts();
  } // get_alerts

  public LocalMonitoringStation.Log[] get_timelogs (long timestamp)
  {
    return _impl.get_timelogs(timestamp);
  } // get_timelogs

  public LocalMonitoringStation.Alert[] get_timealerts (long timestamp)
  {
    return _impl.get_timealerts(timestamp);
  } // get_timealerts

  private LocalMonitoringStation.SensorEventsOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class SensorEventsPOATie
