package LocalMonitoringStation;


/**
* LocalMonitoringStation/SensorEventsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/lms.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public interface SensorEventsOperations 
{
  String lmsname ();
  SensorCamera.Sensor sensor ();
  void record_log (LocalMonitoringStation.Log aLog);
  void record_alarm (LocalMonitoringStation.Alert anAlert);
  LocalMonitoringStation.Log[] get_logs ();
  LocalMonitoringStation.Alert[] get_alerts ();
  LocalMonitoringStation.Log[] get_timelogs (long timestamp);
  LocalMonitoringStation.Alert[] get_timealerts (long timestamp);
} // interface SensorEventsOperations
