package SensorCamera.SensorPackage;

/**
* SensorCamera/SensorPackage/StatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public final class StatusHolder implements org.omg.CORBA.portable.Streamable
{
  public SensorCamera.SensorPackage.Status value = null;

  public StatusHolder ()
  {
  }

  public StatusHolder (SensorCamera.SensorPackage.Status initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SensorCamera.SensorPackage.StatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SensorCamera.SensorPackage.StatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SensorCamera.SensorPackage.StatusHelper.type ();
  }

}
