package SensorCamera.SensorPackage;


/**
* SensorCamera/SensorPackage/StatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

abstract public class StatusHelper
{
  private static String  _id = "IDL:SensorCamera/Sensor/Status:1.0";

  public static void insert (org.omg.CORBA.Any a, SensorCamera.SensorPackage.Status that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SensorCamera.SensorPackage.Status extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (SensorCamera.SensorPackage.StatusHelper.id (), "Status", new String[] { "off", "on"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SensorCamera.SensorPackage.Status read (org.omg.CORBA.portable.InputStream istream)
  {
    return SensorCamera.SensorPackage.Status.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SensorCamera.SensorPackage.Status value)
  {
    ostream.write_long (value.value ());
  }

}
