package SensorCamera.SensorPackage;


/**
* SensorCamera/SensorPackage/Status.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./idl/camera.idl
* Friday, 29 April 2016 00:01:59 o'clock BST
*/

public class Status implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static SensorCamera.SensorPackage.Status[] __array = new SensorCamera.SensorPackage.Status [__size];

  public static final int _off = 0;
  public static final SensorCamera.SensorPackage.Status off = new SensorCamera.SensorPackage.Status(_off);
  public static final int _on = 1;
  public static final SensorCamera.SensorPackage.Status on = new SensorCamera.SensorPackage.Status(_on);

  public int value ()
  {
    return __value;
  }

  public static SensorCamera.SensorPackage.Status from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Status (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Status
